server:
  port: 8087

spring:
  application:
    name: consumer-client-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/

logging:
  level:
    org.springframework.cloud: debug
    com.netflix: debug