sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type : com.alibaba.druid.pool.DruidDataSource
        driver-class: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.10.111.13/dispatcher?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: dispatcher_rw
        password: haoshikisses
        maxPoolSize: 50
        minPoolSize: 1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.10.111.13/heimdallr?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: dispatcher_rw
        password: haoshikisses
        maxPoolSize: 50
        minPoolSize: 1
    config:
      sharding:
        tables: #分片表定义
          t_order: #逻辑表
            actual-data-nodes: ds$->{0..1}.trade$->{0..1}  #数据源.真实表
            database-strategy: # 数据源分片策略
              standard: #标准分片策略
                sharding-column: create_time
                preciseAlgorithmClassName: com.study.sharding.OrderTimeSharding
            table-strategy: # 表分片策略
              inline:
                sharding-column: id # 表分片键
                algorithm-expression: trade$->{id % 2} #分片算法
        default-data-source-name: ds0
      props:
        sql.show: true