sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type : com.alibaba.druid.pool.DruidDataSource
        driver-class: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.10.111.13/dispatcher?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: dispatcher_rw
        password: haoshikisses
        maxPoolSize: 50
        minPoolSize: 1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.10.111.13/heimdallr?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: dispatcher_rw
        password: haoshikisses
        maxPoolSize: 50
        minPoolSize: 1
    config:
      sharding:
        tables: #分片表定义
          t_order: #逻辑表
            actual-data-nodes: ds$->{0..1}.trade  #数据源.真实表
            database-strategy: # 数据源分片策略
              inline: # 行表达式分片策略  ${begin..end} 表示区间 ${[1,2,x]}表示枚举
                sharding-column: customer_id # 分片键
                algorithm-expression: ds$->{customer_id % 2} #分片算法
      props:
        sql.show: true