spring:
  application:
    name: bus-server
  cloud:
    bus:
      destination: bus-test
      trace:
        enabled: true
    stream:
      binders:
        rabbit1:
          type: rabbit
          enviroment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                publisher-confirm-type: correlated
        bindings:
          myInput:
            binder: rabbit1
            destination: things1
          myOutput:
            binder: rabbit1
            destination: things1
          springCloudBusOutput:
            binder: rabbit1
          springCloudBusInput:
            binder: rabbit1