server:
  port: 9999

spring:
  application:
    name: gateway-server
  profiles:
#    active: local
#    active: eureka
    active: dynamic

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
